//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CR.XML.Reader.DB {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RawQuery {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RawQuery() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CR.XML.Reader.DB.RawQuery", typeof(RawQuery).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW DetalleCodigoComercial as 
        ///SELECT  &apos;Factura&apos; as Tipo, * from FacturaDetalleCodigoComercial
        ///union all 
        ///select &apos;Tiquete&apos; as Tipo, * from TiqueteDetalleCodigoComercial
        ///union all 
        ///select &apos;NotaCredito&apos; as Tipo, * from NotaCreditoDetalleCodigoComercial
        ///UNION all 
        ///select &apos;NotaDebito&apos; as Tipo, * from NotaDebitoDetalleCodigoComercial
        ///union all 
        ///select &apos;FacturaCompra&apos; as Tipo, * from FacturaCompraDetalleCodigoComercial
        ///union all 
        ///select &apos;Exportacion&apos; as Tipo, * from ExportacionDetalleCodigoCome [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateComerialCodeView {
            get {
                return ResourceManager.GetString("CreateComerialCodeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW Detalle as 
        ///SELECT  &apos;Factura&apos; as Tipo, * from FacturaDetalle
        ///union all 
        ///select &apos;Tiquete&apos; as Tipo, * from TiqueteDetalle
        ///union all 
        ///select &apos;NotaCredito&apos; as Tipo, * from NotaCreditoDetalle
        ///UNION all 
        ///select &apos;NotaDebito&apos; as Tipo, * from NotaDebitoDetalle
        ///union all 
        ///select &apos;FacturaCompra&apos; as Tipo, * from FacturaCompraDetalle
        ///union all 
        ///select &apos;Exportacion&apos; as Tipo, * from ExportacionDetalle.
        /// </summary>
        internal static string CreateDetailView {
            get {
                return ResourceManager.GetString("CreateDetailView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW Cabecera as 
        ///SELECT  &apos;Factura&apos; as Tipo, * from Factura
        ///union all 
        ///select &apos;Tiquete&apos; as Tipo, * from Tiquete
        ///union all 
        ///select &apos;NotaCredito&apos; as Tipo, * from NotaCredito
        ///UNION all 
        ///select &apos;NotaDebito&apos; as Tipo, * from NotaDebito
        ///union all 
        ///select &apos;FacturaCompra&apos; as Tipo, * from FacturaCompra
        ///union all 
        ///select &apos;Exportacion&apos; as Tipo, * from Exportacion.
        /// </summary>
        internal static string CreateHeaderView {
            get {
                return ResourceManager.GetString("CreateHeaderView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW DetalleImpuesto as 
        ///SELECT  &apos;Factura&apos; as Tipo, * from FacturaImpuesto
        ///union all 
        ///select &apos;Tiquete&apos; as Tipo, * from TiqueteImpuesto
        ///union all 
        ///select &apos;NotaCredito&apos; as Tipo, * from NotaCreditoImpuesto
        ///UNION all 
        ///select &apos;NotaDebito&apos; as Tipo, * from NotaDebitoImpuesto
        ///union all 
        ///select &apos;FacturaCompra&apos; as Tipo, * from FacturaCompraImpuesto
        ///union all 
        ///select &apos;Exportacion&apos; as Tipo, * from ExportacionImpuesto.
        /// </summary>
        internal static string CreateTaxesView {
            get {
                return ResourceManager.GetString("CreateTaxesView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW Resumen as 
        ///SELECT  &apos;Factura&apos; as Tipo, * from FacturaResumen
        ///union all 
        ///select &apos;Tiquete&apos; as Tipo, * from TiqueteResumen
        ///union all 
        ///select &apos;NotaCredito&apos; as Tipo, * from NotaCreditoResumen
        ///UNION all 
        ///select &apos;NotaDebito&apos; as Tipo, * from NotaDebitoResumen
        ///union all 
        ///select &apos;FacturaCompra&apos; as Tipo, * from FacturaCompraResumen
        ///union all 
        ///select &apos;Exportacion&apos; as Tipo, * from ExportacionResumen.
        /// </summary>
        internal static string CreateTotalsView {
            get {
                return ResourceManager.GetString("CreateTotalsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP VIEW &quot;main&quot;.&quot;DetalleCodigoComercial&quot;;.
        /// </summary>
        internal static string DropComercialCodeView {
            get {
                return ResourceManager.GetString("DropComercialCodeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP VIEW &quot;main&quot;.&quot;Detalle&quot;;.
        /// </summary>
        internal static string DropDetailView {
            get {
                return ResourceManager.GetString("DropDetailView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP VIEW &quot;main&quot;.&quot;Cabecera&quot;;.
        /// </summary>
        internal static string DropHeaderView {
            get {
                return ResourceManager.GetString("DropHeaderView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP VIEW &quot;main&quot;.&quot;DetalleImpuesto&quot;;.
        /// </summary>
        internal static string DropTaxesView {
            get {
                return ResourceManager.GetString("DropTaxesView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP VIEW &quot;main&quot;.&quot;Resumen&quot;;.
        /// </summary>
        internal static string DropTotalsView {
            get {
                return ResourceManager.GetString("DropTotalsView", resourceCulture);
            }
        }
    }
}
